// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/network_compute_bridge_service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Bosdyn.Api {

  /// <summary>Holder for reflection information generated from Protos/network_compute_bridge_service.proto</summary>
  public static partial class NetworkComputeBridgeServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for Protos/network_compute_bridge_service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static NetworkComputeBridgeServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CitQcm90b3MvbmV0d29ya19jb21wdXRlX2JyaWRnZV9zZXJ2aWNlLnByb3Rv",
            "Egpib3NkeW4uYXBpGiNQcm90b3MvbmV0d29ya19jb21wdXRlX2JyaWRnZS5w",
            "cm90bzLbAQoUTmV0d29ya0NvbXB1dGVCcmlkZ2USWQoOTmV0d29ya0NvbXB1",
            "dGUSIS5ib3NkeW4uYXBpLk5ldHdvcmtDb21wdXRlUmVxdWVzdBoiLmJvc2R5",
            "bi5hcGkuTmV0d29ya0NvbXB1dGVSZXNwb25zZSIAEmgKE0xpc3RBdmFpbGFi",
            "bGVNb2RlbHMSJi5ib3NkeW4uYXBpLkxpc3RBdmFpbGFibGVNb2RlbHNSZXF1",
            "ZXN0GicuYm9zZHluLmFwaS5MaXN0QXZhaWxhYmxlTW9kZWxzUmVzcG9uc2Ui",
            "ADLhAQoaTmV0d29ya0NvbXB1dGVCcmlkZ2VXb3JrZXISWQoOTmV0d29ya0Nv",
            "bXB1dGUSIS5ib3NkeW4uYXBpLk5ldHdvcmtDb21wdXRlUmVxdWVzdBoiLmJv",
            "c2R5bi5hcGkuTmV0d29ya0NvbXB1dGVSZXNwb25zZSIAEmgKE0xpc3RBdmFp",
            "bGFibGVNb2RlbHMSJi5ib3NkeW4uYXBpLkxpc3RBdmFpbGFibGVNb2RlbHNS",
            "ZXF1ZXN0GicuYm9zZHluLmFwaS5MaXN0QXZhaWxhYmxlTW9kZWxzUmVzcG9u",
            "c2UiAGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Bosdyn.Api.NetworkComputeBridgeReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
