// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/payload_registration_service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Bosdyn.Api {

  /// <summary>Holder for reflection information generated from Protos/payload_registration_service.proto</summary>
  public static partial class PayloadRegistrationServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for Protos/payload_registration_service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PayloadRegistrationServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CilQcm90b3MvcGF5bG9hZF9yZWdpc3RyYXRpb25fc2VydmljZS5wcm90bxIK",
            "Ym9zZHluLmFwaRohUHJvdG9zL3BheWxvYWRfcmVnaXN0cmF0aW9uLnByb3Rv",
            "MrkDChpQYXlsb2FkUmVnaXN0cmF0aW9uU2VydmljZRJaCg9SZWdpc3RlclBh",
            "eWxvYWQSIi5ib3NkeW4uYXBpLlJlZ2lzdGVyUGF5bG9hZFJlcXVlc3QaIy5i",
            "b3NkeW4uYXBpLlJlZ2lzdGVyUGF5bG9hZFJlc3BvbnNlEmkKFFVwZGF0ZVBh",
            "eWxvYWRWZXJzaW9uEicuYm9zZHluLmFwaS5VcGRhdGVQYXlsb2FkVmVyc2lv",
            "blJlcXVlc3QaKC5ib3NkeW4uYXBpLlVwZGF0ZVBheWxvYWRWZXJzaW9uUmVz",
            "cG9uc2USZgoTR2V0UGF5bG9hZEF1dGhUb2tlbhImLmJvc2R5bi5hcGkuR2V0",
            "UGF5bG9hZEF1dGhUb2tlblJlcXVlc3QaJy5ib3NkeW4uYXBpLkdldFBheWxv",
            "YWRBdXRoVG9rZW5SZXNwb25zZRJsChVVcGRhdGVQYXlsb2FkQXR0YWNoZWQS",
            "KC5ib3NkeW4uYXBpLlVwZGF0ZVBheWxvYWRBdHRhY2hlZFJlcXVlc3QaKS5i",
            "b3NkeW4uYXBpLlVwZGF0ZVBheWxvYWRBdHRhY2hlZFJlc3BvbnNlQiFCH1Bh",
            "eWxvYWRSZWdpc3RyYXRpb25TZXJ2aWNlUHJvdG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Bosdyn.Api.PayloadRegistrationReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
